"use client";
import {useEffect,useState} from "react";
import {ArrowRight,ChevronDown,Clock3,Heart,History,Menu,Moon,RotateCcw,Sparkles,Star,ShieldCheck,X} from "lucide-react";

type Reading={headline:string;summary:string;interpretation:string;synthesis:string;reflectionPrompt:string;disclaimer:string;cards:Array<{position:number;name:string}>;source?:string};
type HistoryItem={question:string;reading:Reading;createdAt:string};
const examples=["Czy on do mnie wróci?","Czy powinnam napisać pierwsza?","Co naprawdę dzieje się w tej relacji?","Czy pojawi się ktoś nowy?"];
export default function Home(){const [question,setQuestion]=useState("");const [loading,setLoading]=useState(false);const [reading,setReading]=useState<Reading|null>(null);const [history,setHistory]=useState<HistoryItem[]>([]);const [showHistory,setShowHistory]=useState(false);const [menu,setMenu]=useState(false);
useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem("wrozbita-history")||"[]"))}catch{}},[]);
async function ask(){if(!question.trim()||loading)return;setLoading(true);setReading(null);try{const r=await fetch("/api/reading",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({question})});const d=await r.json();if(!d.ok)throw new Error(d.error||"READING_FAILED");const nextReading=d.reading as Reading;setReading(nextReading);const item={question,reading:nextReading,createdAt:new Date().toISOString()};const nextHistory=[item,...history].slice(0,12);setHistory(nextHistory);localStorage.setItem("wrozbita-history",JSON.stringify(nextHistory))}catch(e){alert("Nie udało się wykonać odczytu. Spróbuj ponownie.")}finally{setLoading(false)}}
function reset(){setReading(null);setQuestion("")}
return <main className="shell">
<div className="ambient ambientA"/><div className="ambient ambientB"/>
<header className="nav"><div className="brand"><div className="brandMark"><Moon size={17}/></div><span>WRÓŻBITA</span><small>AI</small></div><nav className="navLinks"><button onClick={()=>setShowHistory(true)}><History size={16}/> Historia</button><a href="#how">Jak działa</a><a href="#about">O odczycie</a></nav><div className="navActions"><button className="iconButton" onClick={()=>setShowHistory(true)}><History size={17}/></button><button className="menuButton" onClick={()=>setMenu(!menu)}>{menu?<X size={18}/>:<Menu size={18}/>}</button></div></header>
{menu&&<div className="mobileMenu"><button onClick={()=>{setShowHistory(true);setMenu(false)}}>Historia odczytów</button><a href="#how" onClick={()=>setMenu(false)}>Jak działa</a><a href="#about" onClick={()=>setMenu(false)}>O odczycie</a></div>}
<section className="hero"><div className="eyebrow"><Sparkles size={14}/> CORE ENGINE AI <span/> SYMBOLIC READING</div><h1>Masz jedno pytanie.<br/><em>Posłuchaj kart.</em></h1><p className="lead">Wróżbita AI tworzy spersonalizowany, trzykartowy odczyt wokół Twojego pytania. Bez deklarowania pewnej przyszłości. Z naciskiem na kontekst, symbole i refleksję.</p>
<div className="oracleCard"><div className="cardTop"><span>PYTANIE DO WRÓŻBITY</span><span>3 KARTY</span></div><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")ask()}} placeholder="Np. Czy on do mnie wróci?" maxLength={600}/><div className="quick">{examples.map(x=><button key={x} onClick={()=>setQuestion(x)}>{x}</button>)}</div><button className="primary" disabled={!question.trim()||loading} onClick={ask}>{loading?<><RotateCcw size={18} className="spin"/> Przygotowuję odczyt...</>:<>Zapytaj Wróżbitę <ArrowRight size={18}/></>}</button><div className="trust"><span><ShieldCheck size={14}/> prywatny odczyt</span><span><Clock3 size={14}/> około 30 sekund</span><span><Star size={14}/> symboliczna refleksja</span></div></div></section>
{reading&&<section className="reading"><div className="readingHead"><div><div className="eyebrow"><Sparkles size={14}/> TWÓJ ODCZYT</div><h2>{reading.headline}</h2></div><button className="ghost" onClick={reset}>Nowe pytanie <RotateCcw size={15}/></button></div><div className="cards">{reading.cards.map((c,i)=><div className="tarot" key={c.position}><div className="tarotInner"><div className="tarotNum">0{c.position}</div><div className="moonSeal"><Moon size={25}/></div><div className="tarotName">{c.name}</div><div className="tarotLabel">{["SYTUACJA","NAPIĘCIE","KIERUNEK"][i]}</div></div></div>)}</div><div className="readingGrid"><article><span className="sectionLabel">INTERPRETACJA</span><h3>{reading.summary}</h3><p>{reading.interpretation}</p><p>{reading.synthesis}</p></article><aside><span className="sectionLabel">PYTANIE DO REFLEKSJI</span><div className="reflection">“{reading.reflectionPrompt}”</div><div className="divider"/><span className="sectionLabel">NASTĘPNY KROK</span><p>Możesz zadać jedno pytanie uzupełniające i wykonać nowy odczyt.</p><button className="secondary" onClick={()=>{setQuestion("");window.scrollTo({top:0,behavior:"smooth"})}}>Zadaj kolejne pytanie <ArrowRight size={16}/></button></aside></div><p className="disclaimer">{reading.disclaimer}</p></section>}
<section id="how" className="how"><div><span className="sectionLabel">JAK TO DZIAŁA</span><h2>Nie losujemy odpowiedzi.<br/>Budujemy odczyt.</h2></div><div className="steps"><div><b>01</b><strong>Twoje pytanie</strong><p>Silnik rozpoznaje temat i intencję.</p></div><div><b>02</b><strong>Trzy karty</strong><p>Losowanie odbywa się deterministycznie i jest zapisywalne.</p></div><div><b>03</b><strong>Interpretacja AI</strong><p>Core Engine łączy karty z kontekstem pytania.</p></div></div></section>
<section id="about" className="about"><div><Heart size={18}/><span>WRÓŻBITA AI</span></div><p>Produkt wykorzystuje Core Engine jako centralną warstwę routingu, skill runtime i kontrolowaną syntezę AI.</p><span className="fine">Dla rozrywki i autorefleksji. Nie jest narzędziem do podejmowania decyzji medycznych, prawnych ani finansowych.</span></section>
<footer><span>© 2026 Wróżbita AI</span><span>Core Engine AI</span></footer>
{showHistory&&<div className="overlay" onClick={()=>setShowHistory(false)}><div className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><span className="sectionLabel">HISTORIA</span><h3>Twoje odczyty</h3></div><button className="iconButton" onClick={()=>setShowHistory(false)}><X size={18}/></button></div>{history.length===0?<p className="empty">Nie masz jeszcze zapisanych odczytów.</p>:history.map((h,i)=><button className="historyItem" key={i} onClick={()=>{setQuestion(h.question);setReading(h.reading);setShowHistory(false)}}><span>{h.question}</span><small>{new Date(h.createdAt).toLocaleDateString("pl-PL")}</small></button>)}</div></div>}
</main>}